language: node_js
node_js:
  - "6"
  - "6.7"
sudo: required
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - libzmq3-dev

before_install:
  - npm install -g node-gyp

before_script:
  - git submodule update --init

script:
  npm run debug-test
