# MatrixOS development compose file
# It does not define MXSS dependency intentionally so it can use either a locally running
# instance or a remotely running instance, see env.MATRIX_STREAMING_SERVER
version: '2'
services:
  mos:
    build: .
    command: nodemon index.js
    networks:
      - matrixos
    ports:
      - 80:80
    volumes:
      # Mount current directory under /matrix in the container so you can edit code
      # locally and have the changes available inside a running container
      - ./:/matrix
    # @TODO (Sean) Please review which device mappings make sense for OSX here, we then
    # review Linux
    # devices:
    #  - "/dev/ttyUSB0:/dev/ttyUSB0"     
    environment:
      # Reinstall all modules when running docker-entrypoint.sh, helps in avoiding
      # ugly bugs related with bad node_modules
      REINSTALL_NODE_MODULES: 1
    env_file:
      # Define a .env file containing the following environment variables
      # and tweak those according to your current development needs:
      #   - MATRIX_API_SERVER=<admobilize API server>
      #     development server is available @ http://dev-demo.admobilize.com
      #   - MATRIX_STREAMING_SERVER=<your pick here>
      #     * development server is available @ http://dev-mxss.admobilize.com:80
      #     * local running MXSS can be addressed by setting mxss:80
      #   - MATRIX_CLIENT_ID=<your client id>
      #   - MATRIX_CLIENT_SECRET=<your client secret>
      #
      # NOTE 1: it is rude to commit this file as it will overwrite other people devel 
      #         settings
      # NOTE 2: there are zsh extensions to load these files automatically to your environment
      #         when you cd to a directory. Check the gist below for an example
      #         https://gist.github.com/maciekrb/55c2d8f8dfddb8564c1ed926d605251d
      - ./.env

networks:
  matrixos:
