name: face
version: 1
configVersion: 2
description: Matrix face
widgets:
  poop: 123

sensors:
  - camera
  - temperature
  - wobbly

services:
  vehicle:
    engine: vehicle-count
    engineParams:
      zones:
        exitZone:
          x: 100
          y: 100
          width: 100
          height: 200
  face:
    engine: face-detect
    engineParams:
      zone:
        x: 10
        y: 100
        width: 50
        height: 40
