name: face
version: 1
configVersion: 2
description: Matrix face
keywords: face,detect
widgets:
  poop: 123

sensors:
  - camera
  - temperature
  - wobbly

services:
  face:
    engine: face
    engineParams:
      zone:
        x: 10
        y: 100
        width: 50
        height: 40
