
# NOTE: When updating this, update config-basic in config-helper repo

# App Information for Store
name: monitor
version: 1
configVersion: 2
description: Matrix stats

configuration:
  refresh: 1000

dataTypes:
  test: integer
  device:
    'os_hostname': string
    'os_type': string
    'os_platform': string
    'os_arch': string
  monitor:
    cpu: float
    memory: float

# screens are comprised of widgets
screens:

  # Row 1
  - - buttonTest
    - buttonsTest
  #  - buttonOut
  #
  - - pieTest
    - radarTest
    - polarTest
    - cpuChart
  # Row
  - - info
  # Row
  - - cpu
    - memory

widgets:
  info:
    type: device
    display: list-group
  cpuChart:
    type: monitor
    key: cpu
    display: line
    label: CPU Chart
  buttonTest:
    label: Hacking Buttons
    control: button
    trigger: buttonInfo
    value: Get Secret Information
  buttonsTest:
    label: Matrix Activation Buttons
    control: button
    map:
      'amps+': buttonUp
      'amps-': buttonDown
      begin : buttonStart
      end : buttonStop
      capture : buttonSample

      'refresh+' : buttonSlow
      'refresh-' : buttonFast
  buttonOut:
    type: test
    display: digit
  switchTest:
    control: switch
  polarTest:
    type: monitor
    key: cpu
    display: polar
    label: polar bears
  pieTest:
    type: monitor
    key: cpu
    display: pie
    label: CPU Cycles
  radarTest:
    type: monitor
    key: cpu
    display: radar
    label: last CPU
  cpu:
    type: monitor
    key: cpu
    display: digit
    format: round
    label: cpu
  memory:
    type: monitor
    key: memory
    display: digit
    format: round
    label: memory
