
# NOTE: When updating this, update config-basic in config-helper repo

# App Information for Store
name: monitor
version: 1
configVersion: 2
description: Matrix stats

# provided to MatrixOS runtime as Matrix.refresh
configuration:
  refresh: 1000

# these are defined for writing data to the data base
dataTypes:
  device:
    'os_hostname': string
    'os_type': string
    'os_platform': string
    'os_arch': string
  monitor:
    cpu: float
    memory: float

# screens are comprised of widgets
screens:

  # Row 1
  - - buttonsTest
  # Row 2
  - - buttonTest
  # Row 3
  - - info
  # Row
  - - labelGroup
    - dropDown
    - cpuChart
  # Row 4
  - - gaugeChart
    - radarTest
    - barChart
  # Row 5
  - - info
  # Row 6
  - - cpu
    - memory

widgets:
  dropDown:
    # loads < dropdown-control > directive
    control: dropdown
    # maps to app events
    map:
      test1: doTest1
      test2: doTest2
    # label on widget
    label: dropdown test
  labelGroup:
    type: device
    # loads < labeled-group > directive
    display: labeled-group
    label: Label Group
  gaugeChart:
    type: monitor
    # loads < gauge-chart-chartjs > directive
    display: gauge
    # use this key for this widget data ( monitor.cpu )
    key: cpu
    label: Monitoring Gauge
  info:
    type: device
    display: list-group
    label: Secret Information
  cpuChart:
    type: monitor
    keys: cpu,memory
    display: line
    label: CPU Chart
  buttonTest:
    label: Hacking Buttons
    # loads < button-control > directive
    control: button
    # Matrix.on('buttonInfo')
    trigger: buttonInfo
    # Button Label
    value: Get Secret Information
  buttonsTest:
    label: Matrix Activation Buttons
    control: button
    #loads many buttons, label: eventName
    map:
      'amps+': buttonUp
      'amps-': buttonDown
      begin : buttonStart
      end : buttonStop
      capture : buttonSample

      'refresh+' : buttonSlow
      'refresh-' : buttonFast
  barChart:
    type: monitor
    # multi-series keys
    keys: cpu, memory
    # loads < bar-chart-chartjs >
    display: bar
    label: Bar CHart

  buttonOut:
    type: test
    display: digit
  switchTest:
    control: switch
  polarTest:
    type: monitor
    key: cpu
    display: polar
    label: polar bears
  pieTest:
    type: monitor
    key: cpu
    display: pie
    label: CPU Cycles
  radarTest:
    type: monitor
    keys: cpu,memory
    display: radar
    label: last CPU
  cpu:
    type: monitor
    key: cpu
    display: digit
    format: round
    label: cpu
  memory:
    type: monitor
    key: memory
    display: digit
    format: round
    label: memory
